version: "3.2"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: leblum/identity.api:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9001/healthcheck"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - target: 8080
        published: 5000
        protocol: tcp
        mode: ingress
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: